language: go

go:
  - 1.12

install:
    - go get github.com/Urethramancer/daemon
    - go get github.com/Urethramancer/signor

include:
  - os: linux
    go: 1.12.x
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod

